# Generated by Django 2.1.3 on 2018-11-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True, null=True)),
                ('star', models.BooleanField(default=False)),
                ('choice', models.CharField(blank=True, choices=[('task', 'タスク'), ('anime', 'アニメ'), ('book', '本'), ('game', 'ゲーム')], default='task', max_length=10)),
                ('時間', models.DateTimeField(verbose_name='連絡日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
