# Generated by Django 2.1.3 on 2018-11-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='choice',
            field=models.CharField(blank=True, choices=[('1', 'タスク'), ('2', 'アニメ'), ('3', '本'), ('4', 'ゲーム')], max_length=10),
        ),
    ]
