# Generated by Django 2.1.3 on 2018-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181108_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='choice',
            field=models.CharField(blank=True, choices=[('task', 'タスク'), ('anime', 'アニメ'), ('book', '本'), ('game', 'ゲーム')], default='task', max_length=10),
        ),
    ]
